### PR TITLE
Add instructions for OpenSUSE/SLES

### PR DESCRIPTION
**Pull request by Gsantomaggio**

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@lemenkov Can we remove all these docker images for testing and leave only the last one?

Maybe I can create a branch for the "old" versions an one for the last one.

something like:
`v18-20` (with the old docker images)
`master` (with the last one)

**Comment by lemenkov** [comment]
Hello @Gsantomaggio 
I think we should stay with all supported by @erlang versions. I think now supported ones are 20 and 21.

What do you think of keeping ver 20?

**Comment by Gsantomaggio** [comment]
ok yes, it makes sense.

Let me add 20 and 21 to the `master` branch

**Comment by Gsantomaggio** [comment]
@lemenkov done.

We have 20 and 21, and v18/v19 branches for the old versions

**Pull request merged**
