### PR TITLE
Change package version to 1.0

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Fixes https://github.com/systemd/erlang-sd_notify/issues/26

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
Here you can download the binaries:

[packages.zip](https://github.com/systemd/erlang-sd_notify/files/919685/packages.zip)

**Comment by Gsantomaggio** [comment]
@lemenkov please give a try, if they are ok for your side I will tag them and I will attach the binaries

**Comment by lemenkov** [comment]
Looks good to me!

**Comment by Gsantomaggio** [comment]
@lemenkov Great! going to release !

**Comment by Gsantomaggio** [comment]
@lemenkov done: https://github.com/systemd/erlang-sd_notify/releases/tag/v1.0

**Pull request merged**
